name: notification_permission_pro
description: Notification permission handling plugin for Flutter - iOS
version: 1.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: false
        pluginClass: NotificationPermissionPro
